# Numpy exercises

This is a collection of exercises that have been collected in the numpy mailing list, on stack overflow
and in the numpy documentation. The goal of this collection is to offer a quick reference for both old
and new users but also to provide a set of exercises for those who teach.

In this notebook, you will find 30 exercises that are essential to practice and learn numpy. If you want to do further exploration, you can continue working on `02.Extra_Drill_numpy.ipynb`.

#### 1. Import the numpy package under the name `np` (★☆☆)

In [7]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆)

In [8]:
print(np.__version__)
print(np.show_config())

1.20.3
blas_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/include']
blas_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/include']
lapack_mkl_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/include']
lapack_opt_info:
    libraries = ['mkl_rt', 'pthread']
    library_dirs = ['/opt/anaconda3/lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['/opt/anaconda3/include']
None


#### 3. Create a null vector of size 10 (★☆☆)

In [9]:
a = np.zeros(10)
a

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

#### 4. How to find the memory size of any array (★☆☆)

In [10]:
print("Memory size of one array element in bytes: ",
      a.itemsize)

Memory size of one array element in bytes:  8


#### 5. How to get the documentation of the numpy add function from the command line? (★☆☆)

In [11]:
python -c "import numpy; numpy.info(numpy.add)"

SyntaxError: invalid syntax (2787590163.py, line 1)

#### 6. Create a null vector of size 10 but the fifth value which is 1 (★☆☆)

In [ ]:
a= np.zeros(10)
a[4]= 1
print(a)

[0. 0. 0. 0. 1. 0. 0. 0. 0. 0.]


#### 7. Create a vector with values ranging from 10 to 49 (★☆☆)

In [ ]:
x=np.arange(10,50)
print (x)

[10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


#### 8. Reverse a vector (first element becomes last) (★☆☆)

In [ ]:
x = np.arange(10,50)
x= x[::-1]
print (x)

[49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28 27 26
 25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10]


#### 9. Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆)

In [ ]:
x = np.arange(9).reshape(3,3)
print(x)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


#### 10. Find indices of non-zero elements from [1,2,0,0,4,0] (★☆☆)

In [ ]:
non_zero_elements = np.nonzero([1,2,0,0,4,0])
print(non_zero_elements)

(array([0, 1, 4]),)


#### 11. Create a 3x3 identity matrix (★☆☆)

In [ ]:
a =np.eye(3)
print(a)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


#### 12. Create a 3x3x3 array with random values (★☆☆)

In [ ]:
a =np.random.random((3,3,3))
print(a)

[[[0.37551711 0.90380914 0.97978658]
  [0.18928859 0.52939419 0.31097372]
  [0.85523357 0.95199774 0.94889489]]

 [[0.77796841 0.75533597 0.34658049]
  [0.54758838 0.97090646 0.56096596]
  [0.05046699 0.51787947 0.64767526]]

 [[0.44687594 0.70800507 0.57751312]
  [0.27233915 0.01007282 0.0624948 ]
  [0.14159607 0.11571186 0.60068199]]]


#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆)

In [ ]:
a= np.random.random((10,10))
min_value= a.min()
max_value= a.max()
print(min_value, max_value)

0.018990464884968583 0.9909773974838256


#### 14. Create a random vector of size 30 and find the mean value (★☆☆)

In [ ]:
a = np.random.random(size=30)
mean_value = a.mean()
print(a)
print (mean_value)


[0.96749643 0.42685226 0.25697331 0.63436022 0.1412871  0.47528285
 0.80142806 0.94075003 0.17545249 0.72354696 0.15955588 0.1215571
 0.91254504 0.89479512 0.68223345 0.20341985 0.38362045 0.99563337
 0.96111111 0.65947628 0.64088448 0.27799902 0.14106647 0.34159752
 0.74035084 0.06918279 0.49369408 0.13708018 0.60979313 0.30634936]
0.5091791733503119


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆)

In [ ]:
a = np.ones((5,5))
a[1:-1,1:-1]=0
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆)

In [ ]:
x = np.pad(a, pad_width=1, mode='constant', constant_values=0)
print(x)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


#### 17. What is the result of the following expression? (★☆☆)
```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.3 == 3 * 0.1
```

In [ ]:
print(0 * np.nan)
print(np.nan == np.nan)
print(np.inf > np.nan)
print(np.nan - np.nan)
print(0.3 == 3 * 0.1)


nan
False
False
nan
False


#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆)

In [ ]:
a =  np.diag(np.arange(5)[1:],k=-1)
print(a)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆)

In [ ]:
a = np.zeros((8,8),dtype=int)
a[1::2,::2]= 1
a[::2,1::2]= 1
print(a)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element?

In [ ]:
print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


In [ ]:
x= np.arange(336).reshape(6,7,8)
num=x[1][5][4]
print(x)
print("-------------------------------------")
print(num)

[[[  0   1   2   3   4   5   6   7]
  [  8   9  10  11  12  13  14  15]
  [ 16  17  18  19  20  21  22  23]
  [ 24  25  26  27  28  29  30  31]
  [ 32  33  34  35  36  37  38  39]
  [ 40  41  42  43  44  45  46  47]
  [ 48  49  50  51  52  53  54  55]]

 [[ 56  57  58  59  60  61  62  63]
  [ 64  65  66  67  68  69  70  71]
  [ 72  73  74  75  76  77  78  79]
  [ 80  81  82  83  84  85  86  87]
  [ 88  89  90  91  92  93  94  95]
  [ 96  97  98  99 100 101 102 103]
  [104 105 106 107 108 109 110 111]]

 [[112 113 114 115 116 117 118 119]
  [120 121 122 123 124 125 126 127]
  [128 129 130 131 132 133 134 135]
  [136 137 138 139 140 141 142 143]
  [144 145 146 147 148 149 150 151]
  [152 153 154 155 156 157 158 159]
  [160 161 162 163 164 165 166 167]]

 [[168 169 170 171 172 173 174 175]
  [176 177 178 179 180 181 182 183]
  [184 185 186 187 188 189 190 191]
  [192 193 194 195 196 197 198 199]
  [200 201 202 203 204 205 206 207]
  [208 209 210 211 212 213 214 215]
  [216 217 218 219 220

#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆)

In [ ]:
a = np.array([[0,1], [1,0]])
a_tile=np.tile(a,(4, 4))

print(a)
print("-----------")
print(a_tile)

[[0 1]
 [1 0]]
-----------
[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆)

In [ ]:
a = np.random.random((5,5))
print(a)
print("------------")
max_value = a.max()
min_value= a.min()
normal_array= (a-min_value)/(max_value-min_value)
print(normal_array)


[[0.90812378 0.23383559 0.18875266 0.72274402 0.1179508 ]
 [0.88886946 0.62937156 0.02375724 0.27582828 0.96347788]
 [0.27179333 0.36699502 0.18345376 0.1550972  0.29662599]
 [0.84695707 0.54068047 0.238441   0.35298249 0.82603138]
 [0.23164944 0.2684451  0.71877115 0.87556663 0.05986729]]
------------
[[0.94109516 0.22355404 0.17557922 0.74382402 0.10023571]
 [0.92060575 0.64446209 0.         0.26824041 1.        ]
 [0.26394663 0.36525512 0.16994043 0.13976491 0.29037221]
 [0.87600484 0.55008182 0.22845488 0.35034375 0.85373685]
 [0.22122767 0.26038362 0.73959631 0.90644959 0.03842638]]


In [ ]:
#how to do normalization and standardization
def normalization(data):
    _range=np.max(data)-np.min(data)
    return (data-np.min(data))/_range

def standardization(data):
    mu=np.mean(data,axis=0)
    sigma=np.std(data,axis=0)
    return (data-mu)/sigma

#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆)

In [ ]:
color = np.dtype([("R", np.ubyte, 1),
                  ("G", np.ubyte, 1),
                  ("B", np.ubyte, 1),
                  ("A", np.ubyte, 1)])

/var/folders/19/sv_6hbsn0d52kh_xhxmjswxh0000gn/T/ipykernel_2571/2388386340.py:1: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  color = np.dtype([("R", np.ubyte, 1),


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆)

In [ ]:
n1=np.ones((5,3),dtype=int)
n2=np.ones((3,2),dtype=int)
print(n1)
print("--------")
print(n2)
print("--------")
n_multiply=np.dot(n1,n2)
print(n_multiply)


[[1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]
 [1 1 1]]
--------
[[1 1]
 [1 1]
 [1 1]]
--------
[[3 3]
 [3 3]
 [3 3]
 [3 3]
 [3 3]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆)

In [ ]:
a = np.arange(10)
a[(3 < a) & (a < 8)] *= -1
print(a)

[ 0  1  2  3 -4 -5 -6 -7  8  9]


#### 26. What is the output of the following script? (★☆☆)
```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))  # 0+1+2+3+4-1

9


In [ ]:
from numpy import *        #import everything from numpy
print(sum(range(5),-1))    
"""numpy.sum  -1 is the axis argument, 
denoting the last (and only) axis of the array.
so here just show sum(range(5))=0+1+2+3+4"""

10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)
```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z=np.arange(10)
print(Z)    #legal
print(Z**Z)   #legal   #power
print(2 << Z >> 2)  #legal #(x << n == x*(2^n) ) (x >> n == x/2^n) 
print(Z<- Z)  #legal
print(1j*Z)    #legal  #complex number
print(Z/1/1)   #legal
print(Z<Z>Z)   #illegal


[0 1 2 3 4 5 6 7 8 9]
[        1         1         4        27       256      3125     46656
    823543  16777216 387420489]
[  0   1   2   4   8  16  32  64 128 256]
[False False False False False False False False False False]
[0.+0.j 0.+1.j 0.+2.j 0.+3.j 0.+4.j 0.+5.j 0.+6.j 0.+7.j 0.+8.j 0.+9.j]
[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()

In [ ]:
1024 >> 2

256

In [ ]:
""""(x << n == x*2^n )  #(x >> n == x/(2^n)) 
2 << 0 = 2 ,             2 >> 2=0   #result is 0.5, but should be integer,so it output 0
2 << 1 = 4               4 >> 2=1  
2 << 2 = 8               8 >> 2=2
2 << 3 = 16              16>> 2=4
2 << 4 = 32              32>> 2 =8
2 << 5 = 64              64>> 2 = 16
2 << 6 = 128             128>> 2 = 32
2 << 7 = 256             256>> 2 = 64
2 << 8 = 512             512>> 2 = 128
2 << 9 = 1024            1024>> 2 = 256
"""

In [12]:
2 << 0

2

#### 28. What are the result of the following expressions?
```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
print(np.array(0) / np.array(0))
print(np.array(0) // np.array(0))
print(np.array([np.nan]).astype(int).astype(float))

nan
0
[-9.22337204e+18]


/var/folders/19/sv_6hbsn0d52kh_xhxmjswxh0000gn/T/ipykernel_2571/3912170336.py:1: RuntimeWarning: invalid value encountered in true_divide
  print(np.array(0) / np.array(0))
/var/folders/19/sv_6hbsn0d52kh_xhxmjswxh0000gn/T/ipykernel_2571/3912170336.py:2: RuntimeWarning: divide by zero encountered in floor_divide
  print(np.array(0) // np.array(0))


#### 29.  How to round away from zero a float array ?(★☆☆)

In [ ]:


a=np.array([32.11, 51.5, 0.112])
print(np.round(a,0))

[32. 52.  0.]


#### 30. How to find common values between two arrays? (★☆☆)

In [ ]:
array1 = np.array([0, 10, 20, 40, 60])
print("Array1: ",array1)
array2 = [10, 30, 40]
print("Array2: ",array2)
print("Common values between two arrays:")
print(np.intersect1d(array1, array2))

Array1:  [ 0 10 20 40 60]
Array2:  [10, 30, 40]
Common values between two arrays:
[10 40]
